version: "2"

services:
  app:
    build: docker/php
    volumes:
      - ./:/app
    depends_on:
      - db

  #  env_file:
   #   - .env



  nginx:
    image: nginx:1.12-alpine
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - app



  db:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jsondoc
      MYSQL_USER: root
      MYSQL_PASSWORD: Password00